### ISSUE TITLE
[JSSCP][Report][HTN] Patients with any new complications

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#154]
Req Doc - 
https://docs.google.com/spreadsheets/d/1N6pT88Ez2feCK1qSWiRLBko4aKE0wCc7AWwVNRwTD3M/edit#gid=1262509813&range=10:10

- Aggregate Numbers and Line list
- from line list link the case to DEA.
- This report will show the cases where any complication is developed during HTN program but not there at the time of enrolment.

**Comment by garimadosar5** [comment]
QA Notes - 
- Exit/non-exit status is missing.

**Comment by garimadosar5** [comment]
This is showing the numbers only from latest visit. Need to recalculate. Moving this ON HOLD.

**Comment by sachsk** [comment]
on hold due to views are not refreshing

**Comment by garimadosar5** [comment]
QA Notes - 
- % is not matching to 100. We will have to add one more row with followup not done.

**Comment by sachsk** [comment]
% will be more than 100 because an individual may be have more than one complication.
right now "**followup not done**" count is not correct because we have added the decision concept later for the reporting purpose so that decision is not calculated for old followup needs to edit all followup then it will calculate for each individual.
