### ISSUE TITLE
[JSSCP][Report][Diabetes] Patients with any new complications

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#161]
Reference doc - https://docs.google.com/spreadsheets/d/1N6pT88Ez2feCK1qSWiRLBko4aKE0wCc7AWwVNRwTD3M/edit#gid=1367201437&range=16:16

- Aggregate report
- Check for all the filters
- Line listing for the aggregate number
- Link the line listing to DEA.

**Comment by garimadosar5** [comment]
QA Notes - 

% is not matching to 100. We will have to add one more row with followup not done.

**Comment by sachsk** [comment]
% will be more than 100 because an individual may be have more than one complication.
right now **"followup not done"** count is not correct because we have added the decision concept later for the reporting purpose so that decision is not calculated for old followup needs to edit all followup then it will calculate for each individual.
